import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { NextUIProvider } from "@nextui-org/react";
import Navbar from "./component/template/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        {/* <NextUIProvider> */}
        <Navbar />
        {children}
        {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
